### ISSUE TITLE
Beta 1.8.1 mod links

### ISSUE THREAD

**Issue by BaccarWozat** [MCArchive/metarepo#11]
The following mods are all the ones I am able to use in my beta 1.8.1 modpack. All links were working as of March 31st 2017. I have many more mods I downloaded earlier for b1.7.3 and b1.8.1 but did not keep the links. A good place to find links is on Youtube videos about the mod.
----
Robinton's Cubic Chunks: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1273601-1-0-0-robintons-mods#CubicChunks
Armor Stand: http://www.mediafire.com/file/5ez5db8vk7g7j4h/ArmorStand+B1.8.1.zip
Backpacks: http://www.mediafire.com/file/r48dkb8kol1bs9n/backpacks_v1-9_1-8-1_into-mods-folder.zip
Better Clay: http://www.planetminecraft.com/mod/173-better-clay--better-fixed-clay/
Buildcraft 2.2.5: http://www.mod-buildcraft.com/releases/BuildCraft/
Compact Blocks: http://www.mediafiregaming.com/file/l5mnyenubfswpef/%5B1.8.1%5D%281.12%29+CompactBlocks.zip
Compressed Blocks (Only Blocks): http://www.mediafiregaming.com/file/6pncwmhglj42fna/Compressed+Blocks+v3.2+Only+Blocks.rar
Face View: http://www.mediafire.com/?qh1docsig351bv9
Halogen Lights: http://www.mediafire.com/file/sj4r94xsjnrjvhr/HLights
+1.8.1v1.zip
Iron Fence: http://www.planetminecraft.com/mod/iron-fence/
Mod To Dye For: http://www.planetminecraft.com/mod/mod-to-dye-for/
More Stackables: http://www.mediafire.com/file/gspdydfwdeq54su/More+Stackables+B1.8.1.zip
Save Point Chest: http://www.mediafire.com/?dsufgdt4t875u5o
Shelf: http://www.mediafire.com/file/r1wfc61l6tj9vdk/Shelf+B1.8.1.zip
Super Slopes: https://www.dropbox.com/s/rrvt490ejz2k9gr/Kaevator_SuperSlopes_v2.3_MC_1.8.1.zip?dl=0
Treecapitator and Zeppelin: Only found in the Technic 4.4.0 modpack:
http://www.mediafire.com/file/jglelxeeq2j2emg/Technic4.4.0.rar
----
List of b1.8.1 mods which I have but do not have the link:
Anvil Mod
Arkidillo's Xtra Ores
Beton (French mod, adds a smooth stone block)
Bettercraft
Block It Made
Brown Bricks (recipe doesn't work)
CampCraft Single Player
CampCraft Lantern 0.1
CampCraft Sleeping bag 0.2
Carpet Mod (5 carpets)
Carpet Mod (16 carpets; different mod author)
Civilization v2 (adds a mob)
Decoratives 1.1.1
Dyed Blocks
Fantasy of Minecraft v2
Great Wall 2.1.2
Increased View Distance (Light and Extreme variations)
Kaevator's CCTV v2.2
Kaevator's Timber Framing v1.5
Kaevator's Wallpaper v1.2
Lag Spike of Death (included in Optifine?)
Land Pirates Mod
Lapis
Magic Blocks and Ores v10
Marbles v2.0
Materia
Mighty Pork
MineFactory Reloaded 1.3.2
Mo' Items v14
Moar Glass
More Halfslabs
More Blocks Mod
Mystic Ores
Mystic Ruins
Mystic Stones (Rare)
Nether Tools v5
Nether Tools 20 (different author)
Oblivion Mod v12
Obsidian Mods v2.1
ObsidianPlus v30
Ores Mod v4
Pac's Lantern Mod v12
Portal Gun v1
Ruby Mod
Saphire Mod (sic)
SDK's Grappling Hook v1
SDK's Guns v1
SDK's Mods v1
SDK's Utility v1
Shaped Charges 1.1.1
Slabs 12
Stargate v1.2
Steam Companion 1.2
Steamcraft v0.5.4
Tale Of Kingdoms v1.0.3
Titanium Mod
Turret Mod
Vampyres v1
Walled City
Weeping Angel v14
Wireless Redstone
Wooden Boards v1.1 (makes thin wood walls like glass panes)

**Comment by Forkk** [comment]
Thanks for the links, but GitHub Issues is not a discussion board, it's only for bugs/feature requests. If you want to talk to us, please join us on [discord](https://discord.gg/0k2zsXGNHs0fE4Wm).
