### ISSUE TITLE
I have a couple mods

### ISSUE THREAD

**Issue by CrankySupertoon** [MCArchive/metarepo#15]
there in my project located here https://sourceforge.net/projects/minecraft-mod-archive/files/

**Comment by CrankySupertoon** [comment]
and just so you know I pull all my mods from this website. http://chomikuj.pl/ . Its like a open source dropbox. I would use chrome because I think its in spansih and it can auto translate it to english

**Comment by CrankySupertoon** [comment]
if you want any mod from any verison ask me I can probally get it :)

**Comment by CrankySupertoon** [comment]
One of my indexes are here http://chomikuj.pl/arek_zareba/*23*23M*c3*b3j+Chomik/*23Gry+Komputerowe/Minecraft/Mody but I cant find my super index where I found very achinet stuff

**Comment by Forkk** [comment]
GitHub Issues is not a discussion board, it's only for bugs/feature requests. If you want to talk to us, please join us on [discord](https://discord.gg/0k2zsXGNHs0fE4Wm).
