### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by CodeArtha** [MCArchive/metarepo#23]
So how exactly do we contribute? I have a huge backup with all my instances going back to stable 1.1. Most of them have mods, and lot o'em. Some probably still have official access, others don't.

Do we edit the JSON files with links for the modfile residing on my own server then Pull request? Or do you prefer centralizing them on your own servers?

Anyways, if everybody starts uploading mod files how do you check they are working, valid and not trolls? Need moderators? (I could help)

Do you plan on keeping only the latest version of the mod for each mcversion?

**Comment by casept** [comment]
+1, I'm building a simple go program which is supposed to take some of the tedium out of manually editing the .json files, and I'd greatly benefit if, for example, documentation existed which states which fields, hash algorithms etc. are required. While a lot can be guessed from currently contributed files official documentation would be much appreciated.

**Comment by CodeArtha** [comment]
Yeah there are a few field that looks like hashes but I have no clue to what algo was used. And there needs to be a centralised place to upload files that don't exist on the official websites anymore.
Which raise the question of their licence? Should we try to contact modauthors to have their agreement?

**Comment by casept** [comment]
The "archived": and "sha256": hashes are both SHA256 in hexadecimal representation (default of most utilities). The "ipfs": field is for an interplanetary file system hash. Basically it's a way to retrieve the mod by it's hash as long as at least one user is "seeding", similar to bittorrent. That's also I believe the longterm strategy for hosting the mods, as well as the place where you should upload files which are no longer hosted by upstream.

**Comment by LostOfThought** [comment]
If there is no currently active DDL from the mod author, leave it out, Use IPFS instead.

Latest version for each MC version is priority, however others are accepted.

We don't exactly have moderation at the moment other than Forkk denying a PR. No automatic verification is in place.

**Comment by brodycas3** [comment]
It would also be nice if you could upload the instances here, perhaps you can upload them with https://nya.is

**Comment by LostOfThought** [comment]
ipfs is the preferred way to upload mods that are no longer hosted and ultimately the way we plan to 'host' everything.
Until we get proper documentation underway, we have a channel on the MultiMC discord at https://discord.gg/cVttf that would be one of the easiest ways to get in contact with the current contributors as a whole (archivist roll).

**Comment by Forkk** [comment]
We can finally answer this question. Here is the documentation:
- [metadata format](https://github.com/MCArchive/metarepo/wiki/Metadata-Format)
- [IPFS](https://github.com/MCArchive/metarepo/wiki/IPFS)
- [contributing guidelines](https://github.com/MCArchive/metarepo/wiki/Contributing)
