### ISSUE TITLE
The meta repo needs a CI job to check pull requests

### ISSUE THREAD

**Issue by peterix** [MCArchive/metarepo#54]
Reviewing pull requests is close to impossible, because the formats used are simply not human friendly -- not even for developers.
So, we need a way to check pull requests automatically.

Proposed approach:
1. write a schema for checking meta files (json/yaml)
2. write a script that takes the metadata repo and validates all meta files
2. set up a CI job to make github check pull requests using the schema (for example by triggering travis-ci)

The schema and script should also be versioned -- we can either put it in a separate repo, or keep it in the metarepo.

**Comment by AffeAli** [comment]
@peterix I have a WIP application here: https://gitlab.com/nickre/mcarchive-cli. I'm currently trying to get it working in travis-ci.
